### ISSUE TITLE
Upgrade to GHC 8.8.2 (incompatible base version)

### ISSUE THREAD

**Issue by tuomohopia** [marcelbuesing/sendgrid-v3#12]
I'm getting an error like this when I bumped `stack.yaml` resolver to `lts-15.0`:

```
In the dependencies for sendgrid-v3-0.1.2.0:
    base-4.13.0.0 from stack configuration does not match >=4.8 && <4.13  (latest matching version is 4.12.0.0)
needed due to project-api-0.1.0.0 -> sendgrid-v3-0.1.2.0
```

`lts-15.0` uses GHC 8.8.2. Would this mean that currently `sendgrid-v3` is incompatible with the latest GHC version because it has a dependency to `base` <4.13 while GHC 8.8.2 comes with `base` 4.13 ?

**Comment by tuomohopia** [comment]
Looks like this PR might comfortably fix this:
https://github.com/marcelbuesing/sendgrid-v3/pull/14

**Comment by donatello** [comment]
This can be closed.

**Comment by donatello** [comment]
Closing as fixed.
