### ISSUE TITLE
Please add this library to stackage

### ISSUE THREAD

**Issue by donatello** [marcelbuesing/sendgrid-v3#13]
Request you to add this library to stackage so it is easier to use in other projects.

https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by mjgpy3** [comment]
@marcelbuesing is this something you'd be willing to do?

**Comment by marcelbuesing** [comment]
@mjgpy3 I would actually be grateful if someone else could look into this so  commercialhaskell/stackage#5951 sounds like a good idea to me! Let me know if there is anything I can help with on that regard. I am also open to moving or copying the project to a separate organization if this helps with maintenance on this project.

**Comment by mjgpy3** [comment]
Hey @marcelbuesing, Freckle would be happy to take over maintenance of this project!

If you're interested you can transfer the repo to `https://github.com/freckle`. Also, on hackage you can add [FreckleEngineering](https://hackage.haskell.org/user/FreckleEngineering) as a maintainer.

**Comment by marcelbuesing** [comment]
@donatello and @pbrisbin would that be ok for you, I assume you are also affected? So the options I see are:

- Transfer ownership to the freckle organization. Not sure how this would affect projects referencing the github repository.
- Archive the current one adding a note to the README that the project moved to the freckle org, make a copy or fork to the freckle org
- Add @mjgpy3 to hackage and this project, so basically leave it as it is but extend the number of maintainers

**Comment by donatello** [comment]
Yes , this works for me. Thanks!

**Comment by pbrisbin** [comment]
I don't feel strongly and all those options sound good to me.

GitHub is good about moving ownership; anything referencing `marcelbuesing/sendgrid-v3` (browser, clone) will find `freckle/sendgrid-v3` and cloning even prints a banner saying to update your remote. We can also re-add @marcelbuesing and @donatello as Collaborators so they can contribute to the project in the new location.

Archive/fork just feels like transfering ownership but with more complexity and disruption. In that option, projects referencing this github repository _would_ need to update themselves or be disrupted. So I'm a soft-no on that option.

Freckle is really only looking to keeping this compiling and in Stackage, so expanding maintainers to include us on Hackage is attractive as it's a smaller change and enables us to do what we need.

**Comment by marcelbuesing** [comment]
Ok I just added you @mjgpy3 to the list of GH repository and hackage maintainers.

**Comment by mjgpy3** [comment]
Thanks @marcelbuesing!

**Comment by mjgpy3** [comment]
I also added FreckleEngineering to the hackage mantainers. I believe that commercialhaskell/stackage#5951 resolves this particular issue (eventually) unless I'm mistaken. @pbrisbin do you know if anything else needs to be done for getting this to stackage?

**Comment by donatello** [comment]
Closing this - since the last discussion, this package was included in stackage and removed later due to failure to build with newer GHC versions. We need to re-add it, after making a new release on hackage.
