### ISSUE TITLE
Deployment to hackage is not happening automatically via Travis CI

### ISSUE THREAD

**Issue by donatello** [marcelbuesing/sendgrid-v3#16]
Please see: https://travis-ci.org/github/marcelbuesing/sendgrid-v3/builds/652889842#L3289

Not sure why this happened, maybe the tag was created after the commit was pushed. I suggest to delete and re-create the tag via command line and push it with (the following untested commands):

```shell
git tag -d 0.3.0.0
git tag -a -m 'tag message' 0.3.0.0 aaacc77130c07182b4888332e7815f80c436318e
git push origin --tags
```

IIUC this should trigger a CI run and cause the deployment to run, publishing to hackage.

**Comment by domenkozar** [comment]
cc @marcelbuesing

**Comment by donatello** [comment]
Closing this - we can manually make releases for now as more maintainers have been added on hackage.
