### ISSUE TITLE
Return the API Response Body in sendMail

### ISSUE THREAD

**Issue by 5outh** [marcelbuesing/sendgrid-v3#6]
:wave: !

The `sendMail` function defined [here](https://github.com/marcelbuesing/sendgrid-v3/blob/163cfc0c61c64b35d06e1b6085d42f163bd2dd3b/src/Network/SendGridV3/Api.hs#L419-L431) does not return the response body from SendGrid.

In the case of errors, this is a problem: if SendGrid will not accept an API request, I'd like to be able to log and/or handle those errors based on the response body given.

**Comment by marcelbuesing** [comment]
Hi, that sounds like a valid point. I'm quite busy right now but feel free to create a PR.
